# Generated by Django 2.2.2 on 2024-05-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190729_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassinfo',
            name='level_short_form',
            field=models.CharField(max_length=10, default=''),  # Cambiado para proporcionar un valor predeterminado
            preserve_default=False,
        ),
    ]
