# Generated by Django 4.0.5 on 2024-05-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentclassinfo_class_short_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclassinfo',
            options={'verbose_name_plural': 'Level List'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'Student List'},
        ),
        migrations.AlterModelOptions(
            name='studentsectioninfo',
            options={'verbose_name_plural': 'Group List'},
        ),
        migrations.AlterModelOptions(
            name='studentshiftinfo',
            options={'verbose_name_plural': 'Shift List'},
        ),
    ]
