# Generated by Django 4.2.5 on 2024-05-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentclassinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'Athlete List'},
        ),
    ]
