# Generated by Django 4.2.5 on 2024-05-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentinfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='student_img',
            new_name='athlete_img',
        ),
    ]
