# Generated by Django 4.0.5 on 2024-05-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherdeptinfo',
            options={'verbose_name_plural': 'Department List'},
        ),
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name_plural': 'Coaches List'},
        ),
        migrations.AlterModelOptions(
            name='teacherdivinfo',
            options={'verbose_name_plural': 'Division List'},
        ),
    ]
